export const DEFAULTS: Record<string, any> = {
  text: { title: "Texto", description: "Envie uma mensagem" },
  Text: { title: "Texto", description: "Envie uma mensagem" },
  start: { title: "Start" },
  message: { title: "Message", text: "Olá! 👋" },
  question: {
    title: "Question",
    prompt: "Deseja continuar?",
    options: [
      { id: "yes", label: "Sim" },
      { id: "no", label: "Não" },
    ],
  },
  options: {
    title: "Opções",
    options: [
      { id: "opt1", label: "Opção 1" },
      { id: "opt2", label: "Opção 2" },
      { id: "opt3", label: "Opção 3" },
    ],
  },
  Options: {
    title: "Opções",
    options: [
      { id: "opt1", label: "Opção 1" },
      { id: "opt2", label: "Opção 2" },
      { id: "opt3", label: "Opção 3" },
    ],
  },
  backgroundProcess: {
    title: "Processo",
    description: "Executa em segundo plano",
    subscriptionName: "",
    subscriptionTopicName: "",
    topicName: "",
    metadata: {},
    requestContent: {},
    responseContent: {},
    startup: false,
  },
  BackgroundProcess: {
    title: "Processo",
    description: "Executa em segundo plano",
    subscriptionName: "",
    subscriptionTopicName: "",
    topicName: "",
    metadata: {},
    requestContent: {},
    responseContent: {},
    startup: false,
  },
  redirect: { title: "Redirecionar", flowId: "outro-fluxo" },
  Redirect: { title: "Redirecionar", flowId: "outro-fluxo" },
  supportTicket: { title: "Ticket de Suporte", department: "Atendimento", priority: "Alta" },
  SupportTicket: { title: "Ticket de Suporte", department: "Atendimento", priority: "Alta" },
  endConversation: {
    title: "Encerrar Conversa",
    description: "",
    subscriptionName: "",
    subscriptionTopicName: "",
    topicName: "",
    metadata: {},
    requestContent: {},
    responseContent: {},
    startup: false,
  },
  EndConversation: {
    title: "Encerrar Conversa",
    description: "",
    subscriptionName: "",
    subscriptionTopicName: "",
    topicName: "",
    metadata: {},
    requestContent: {},
    responseContent: {},
    startup: false,
  },
  proxy: { title: "Proxy", endpoint: "https://proxy.seuservico.com/rota", method: "POST" },
  Proxy: { title: "Proxy", endpoint: "https://proxy.seuservico.com/rota", method: "POST" },
  condition: { title: "Condition", expression: "ctx.ok === true" },
  delay: { title: "Delay", ms: 1000 },
  api: { title: "API", url: "https://api.example.com", method: "GET" },
  end: { title: "End" },
};
